# Generated by Django 4.2.1 on 2023-06-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_staffmember_company_position'),
    ]

    operations = [
    ]
