# Generated by Django 4.2.1 on 2023-07-01 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concesionariaApp', '0006_city_office_city'),
        ('users', '0012_alter_staffmember_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concesionariaApp.city'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concesionariaApp.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concesionariaApp.city'),
        ),
    ]
