version: "3"
services:
    web:
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        container_name: django_server
        ports:
            - "8010:8010"
        volumes:
            - .:/app
        command: >
            sh -c "python manage.py migrate
                  python manage.py runserver 0.0.0.0:8010"
        environment:
            DB_HOST: db
            DB_NAME: app
            DB_USER: postgres
            DB_PASSWORD: 123456
        depends_on:
            - db

    db:
        image: postgres:10-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
        ports:
            - "5432:5432"
        volumes:
            - /datadir:/var/lib/postgresql/data
    aprrka:
        restart: always
        build: .
        depends_on:
            - web