# Generated by Django 4.2.1 on 2023-06-24 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concesionariaApp', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
        migrations.AddField(
            model_name='sale',
            name='officeID',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='concesionariaApp.office'),
        ),
        migrations.AddField(
            model_name='sale',
            name='seller_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.seller'),
        ),
        migrations.AddField(
            model_name='sale',
            name='vehicle_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='concesionariaApp.vehicle'),
        ),
        migrations.AddField(
            model_name='officeaddress',
            name='officeID',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='concesionariaApp.office'),
        ),
    ]
