# Generated by Django 4.2.1 on 2023-06-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concesionariaApp', '0003_office_remove_client_user_id_client_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officemanager',
            name='office',
        ),
        migrations.RemoveField(
            model_name='officemanager',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='OfficeManager',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
