# Generated by Django 4.2.1 on 2023-07-03 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_client_city_staffmember_city_user_city'),
        ('concesionariaApp', '0007_vehicle_vehiclequotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclequotation',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.staffmember'),
        ),
    ]
