# Generated by Django 4.2.1 on 2023-06-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230630_0543'),
    ]

    operations = [
    ]
