# Generated by Django 4.2.1 on 2023-06-30 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concesionariaApp', '0005_companyposition'),
        ('users', '0011_auto_20230630_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionariaApp.office'),
        ),
    ]
