# Generated by Django 4.2.1 on 2023-06-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionariaApp', '0004_remove_officemanager_office_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
