# Generated by Django 4.2.1 on 2023-07-02 20:23

import concesionariaApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_client_city_staffmember_city_user_city'),
        ('concesionariaApp', '0006_city_office_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('hp', models.FloatField()),
                ('torque', models.FloatField()),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to=concesionariaApp.models.vehicle_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionariaApp.city')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionariaApp.office')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionariaApp.vehicle')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staffmember')),
            ],
        ),
    ]
